name: NedoMurderMystery
version: 1
author: nedoprogrammer
main: me.nedoprogrammer.murderMystery.MurderMystery
api-version: 1.12.2
commands:
  mmcreate:
    description: Начать создание новой игры.
    usage: /mmcreate название игры
    permission: nedomurdermystery.create
  mmlobby:
    description: Задать лобби игры.
    usage: /mmlobby название игры
    permission: nedomurdermystery.setlobby
  mmplayers:
    description: Задать максимальное количество игроков для игры.
    usage: /mmplayers название игры | максимум игроков
  mmworld:
    description: Задать начальную точку игры.
    usage: /mmworld название игры
    permission: nedomurdermystery.setworld
  mmsave:
    description: Сохранить игру в файл.
    usage: /mmsave название игры
    permission: nedomurdermystery.save
  mmstart:
    description: Начать ожидание игроков для игры.
    usage: /mmstart название игры
    permission: nedomurdermystery.start
  mmjoin:
    description: Присоединиться к игре.
    usage: /mmjoin название игры
    permission: nedomurdermystery.join
  mmleave:
    description: Выйти из игры.
    usage: /mmleave название игры
    permission: nedomurdermystery.leave